source "https://rubygems.org"

gem "addressable", ">= 2.8.0"
gem "middleman", "~> 4.4.0"
gem "middleman-autoprefixer"
gem "middleman-blog"
gem "middleman-livereload"
gem "middleman-minify-html"
gem "middleman-syntax"
gem "middleman-gh-pages"
gem "redcarpet", ">= 3.5.1"
gem "pry"
